#!/usr/bin/env node

'use strict';

const debug = require('debug')('egg-scripts:start-cluster');

const options = JSON.parse(process.argv[2]);
debug('start cluster options: %j', options);
require(options.framework).startCluster(options);

// TODO: use argv title at process title
